ci: adjust semgrep faillure mode

diff --git a/.github/workflows/sast.yml b/.github/workflows/sast.yml
--- a/.github/workflows/sast.yml
+++ b/.github/workflows/sast.yml
@@ -27,3 +27,9 @@ jobs:
         with:
           sarif_file: semgrep.sarif
           category: semgrep
+      # Pour la lisibilité :)
+      - name: Seuil de blocage
+        if: steps.semgrep.outcome == 'failure'
+        run: |
+          echo "::error::Semgrep a remonte des findings bloquants"
+          exit 1
